"""Hailo-10H shared inference services."""

from .ha_action_verification import install as _install_ha_action_verification
from .ha_pipeline import install as _install_ha_pipeline
from .ha_prompt_compiler import install as _install_ha_prompt_compiler
from .ha_routing import install as _install_ha_routing
from .ha_semantic_routing_fixes import install as _install_ha_semantic_routing_fixes
from .ha_state_routing import install as _install_ha_state_routing
from .ha_state_routing_fixes import install as _install_ha_state_routing_fixes
from .ha_weather_routing import install as _install_ha_weather_routing
from .litert_optimizations import install as _install_litert_optimizations

_install_litert_optimizations()
_install_ha_routing()
_install_ha_state_routing()
_install_ha_state_routing_fixes()
_install_ha_action_verification()
_install_ha_prompt_compiler()
_install_ha_semantic_routing_fixes()
_install_ha_weather_routing()
del _install_litert_optimizations
del _install_ha_routing
del _install_ha_state_routing
del _install_ha_state_routing_fixes
del _install_ha_action_verification
del _install_ha_prompt_compiler
del _install_ha_semantic_routing_fixes
del _install_ha_weather_routing


_install_ha_pipeline()
del _install_ha_pipeline
